Repository acep-devops/tf-github, pull requests merged in 2022-06, with the labels that each got.

#10 Apache Airflow → Initialize Repository
  CHANGELOG.md
  terraform.tfvars.json
Labels: enhancement

#12 feat: add dgpalmieri to admins and remove imthegngrbrdmn
  CHANGELOG.md
  terraform.tfvars.json
Labels: enhancement, help wanted

#13 remove matt :(
  terraform.tfvars.json
Labels: bug

#16 feat: add emr65df to developers
  CHANGELOG.md
  terraform.tfvars.json
Labels: enhancement
