Repository acep-devops/tf-github, pull requests merged in 2022-07, with the labels that each got.

#17 Grafana as Code (GaC) → Initialize Repository
  CHANGELOG.md
  terraform.tfvars.json
Labels: enhancement

#21 Initialization settings for Airflow sprint 🔧
  CHANGELOG.md
  modules/repo/main.tf
  terraform.tfvars.json
Labels: enhancement

#23 merge main into my branch
  CHANGELOG.md
  README.md
  modules/repo/main.tf
  terraform.tfvars.json
Labels: enhancement, question

#25 fix: remove existing repo
  CHANGELOG.md
  terraform.tfvars.json
Labels: bug

#26 Update readme
  CHANGELOG.md
  README.md
Labels: documentation, enhancement
